apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mini-ai-cloud.fullname" . }}-control-plane
  namespace: {{ include "mini-ai-cloud.systemNamespace" . }}
  labels:
    {{- include "mini-ai-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mini-ai-cloud.fullname" . }}-worker
  namespace: {{ include "mini-ai-cloud.systemNamespace" . }}
  labels:
    {{- include "mini-ai-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
